### ISSUE TITLE
Client-Side SDK

### ISSUE THREAD

**Issue by SamKr** [featbit/featbit-dotnet-sdk#14]
Hi team,

You mention the following:

> It is not intended for use in desktop and embedded systems applications.

As this will be my primary usecase: are there plans to release a client-side SDK for use in desktop applications? If not, what would you recommend?

Thank you for this great platform, really enjoy using it :)

**Comment by deleteLater** [comment]
Hi @SamKr, sorry for the late reply. I didn't notice this issue in time because GitHub didn't notify me :sweat_smile: . Can I know more about your tech stack? Did you use MAUI, WinUI, WPF or something else?

**Comment by SamKr** [comment]
No worries! I'm building a WPF standalone application. For the moment I'm using this SDK with a server key, but it feels weird not to use the client key. However, that's purely because of the semantics, because I'm not yet familiar with what the difference is. Assuming the user extracts the server key, what could he do with it? Just query flags, or view and/or change settings? What's the difference in permissions between a server and client key?

Thanks for your time 👋

**Comment by deleteLater** [comment]
For client key and server key: 

- **A client key is intended to be used in the client SDK, while a server key is intended to be used in the server SDK**. There's no functional difference between them so far, we extract the `envId` from the client/server `key`, and then the Client Side SDK use the `envId` to get the calculated flag values for a specific user directly, the Server Side SDK use the `envId` to get the feature flags & segments data, store them in memory then locally calculate the flag value for a user.
- A client key is easier to leak compared to a server key, and usually we don't want a client side app to get the original flags & segments data.

We will do some permission limitations on the client key in the near future, for example disallow using a client key to get the original feature flags & segment data, which means a client key cannot be used in a server-side SDK.

Ideally, we should use a `featbit-dotnet-client-sdk` in your WPF app, but we don't have one yet, so you can

- Use the dotnet-server-sdk with a server key
- Use this [API](https://docs.featbit.co/sdk/retrieve-feature-flags-with-api#client-side) to retrieve flag values for a user. (Use this API to implement a long polling mechanism if you need)

**Comment by SamKr** [comment]
Thanks for the clear explanation @deleteLater :) I'll use the API for now, and hopefully the `featbit-dotnet-client-sdk` somewhere in the future. Cheers

**Comment by deleteLater** [comment]
Yep! And it'll be helpful if you create a feature request issue [here](https://github.com/featbit/featbit/issues/new/choose) when you have a moment, so that we can track this feature easier.

**Comment by SamKr** [comment]
Done

**Comment by deleteLater** [comment]
`FeatBit.ClientSdk` is now available here: https://github.com/featbit/featbit-dotnet-client-sdk
