### ISSUE TITLE
feature request: disable event collection

### ISSUE THREAD

**Issue by ghelyar** [featbit/featbit-dotnet-sdk#20]
We would like to be able to disable event collection when using the FeatBit Server SDK for .NET.

https://github.com/featbit/featbit/issues/531 would also solve this, but is a bigger change.

If we could just construct a `FbClient` with a `NullEventProcessor` but keep the `WebSocketDataSynchronizer` that would solve it for us, but right now it's either fully online or fully offline.

The reason for this is just that we want to get flags into an existing system that is already under load and enable events after, starting with services that are under less load and would produce fewer events. We're primarily interested in flags and events are nice to have but add risk.

This could be done with an extra flag on the options (defaulting to current behaviour), for example.

It could also be done by using a different URI like `urn:featbit:null` which would not affect the API surface but is a bit less intuitive.

I'm happy to submit a pull request if needed.

**Comment by deleteLater** [comment]
make sense for me. I think we just need to add a new option to `FbOptions`, maybe called `DisableEvents`, then

```csharp
_eventProcessor = _options.Offline || _options.DisableEvents
    ? new NullEventProcessor()
    : new DefaultEventProcessor(options);
```
